select * from jz_provide_info

--
SELECT NVL(COUNT(1), 0) COUNT
  FROM JZ_PROVIDE_INFO
 WHERE PROVIDE_FLAG LIKE '1%'
   AND STATUS NOT LIKE 'P%'   --补发状态：P010(新增)、P030(标准调整的补差)、P040(支内回沪资金补发)
--改
select * from jz_provide_info where provide_flag like '1%' and status not like 'P%'

select * from jz_provide_info where person_name = '117'





SELECT NVL(SUM(COUNT), 0) COUNT
  FROM (SELECT NVL(COUNT(1), 0) COUNT
          FROM JZ_MONTH_FINISH_APPLYS B, JZ_INCOMECHECK_STATUS EA, JZ_APP A
         WHERE ((TRUNC(EA.UPDATE_TIME) < TRUNC(B.CREATE_TIME) AND
               TRUNC(B.NEXT_MONTH_TIME) = TRUNC(?) AND
               B.ORGAN_ID = A.ORGAN_ID AND (EA.RECEIVE_STATUS = ?)))
           AND A.ENTRUST_ID = EA.ENTRUST_ID
           AND A.STATUS_ID = ?
           AND A.MANAGE_PROGRAM_ID = ?
           AND A.ORGAN_ID = ?
        UNION ALL
        SELECT NVL(COUNT(1), 0) COUNT
          FROM JZ_INCOMECHECK_ENTRUST_APP EP, JZ_APP B
         WHERE EP.ENTRUST_ID = B.ENTRUST_ID
           AND EP.RECEIVE_STATUS IN (?, ?)
           AND B.STATUS_ID = ?
           AND B.MANAGE_PROGRAM_ID = ?
           AND B.ORGAN_ID = ?)
select * from JZ_MONTH_FINISH_APPLYS; --救助结束本月申请表
select * from JZ_INCOMECHECK_STATUS;  --核对状态表
select * from JZ_INCOMECHECK_ENTRUST_APP; --收入核对申请表
select * from jz_app         
--
SELECT NVL(COUNT(1), 0) COUNT FROM JZ_MONTH_FINISH_APPLYS B, JZ_INCOMECHECK_STATUS EA, JZ_APP A
   WHERE ( ( TRUNC(EA.UPDATE_TIME) < TRUNC(B.CREATE_TIME) AND   --更新状态时间、创建时间
            TRUNC(B.NEXT_MONTH_TIME) = TRUNC(to_date('2018-03','YYYY-MM')) AND       --下个工作月份
            B.ORGAN_ID = A.ORGAN_ID AND (EA.RECEIVE_STATUS = '07') ) --街道*2、街道核对中心确认状态
         )
     AND A.ENTRUST_ID = EA.ENTRUST_ID  --核对编号、委托编号
     AND A.STATUS_ID = 's002' AND A.MANAGE_PROGRAM_ID = '00010001' AND A.ORGAN_ID = '0026102000' --核对编号、管理程序、街道
  UNION ALL
  SELECT NVL(COUNT(1), 0) COUNT FROM JZ_INCOMECHECK_ENTRUST_APP EP, JZ_APP B
   WHERE EP.ENTRUST_ID = B.ENTRUST_ID AND EP.RECEIVE_STATUS IN ('09', '04') --委托编号、核对编号、核对状态
     AND B.STATUS_ID='s002' AND B.MANAGE_PROGRAM_ID='00010001' AND B.ORGAN_ID='0026102000'
     --状态标识、管理程序、街道

cur,
SalvationConstant.CHECK_RECEIVE_STATUS_FINAL_REPORT, --街道核对中心确认状态-07:终核报告已返回："07"
SalvationConstant.OPERATE_STATUS_TOSURVEY, -- 操作状态，待录入调查结果：s002
SalvationConstant.DIBAO_MANAGE_TYPE, --管理程序，低保：00010001
organId, --街道
SalvationConstant.CHECK_RECEIVE_STATUS_QUXIAO_REPORT, --街道核对中心确认状态-09:取消委托成功
SalvationConstant.CHECK_RECEIVE_STATUS_REFUSE_ENTRUST,-- 街道核对中心确认状态-04:不接受委托
SalvationConstant.OPERATE_STATUS_TOSURVEY, -- 操作状态，待录入调查结果：s002
SalvationConstant.DIBAO_MANAGE_TYPE,       --管理程序，低保：00010001
organId                                    ----街道


select * from  jz_jz01
select * from JZ_GASWBD_BDJG
select * from jz_provide_info













--待新受理审核
SELECT A.CETF_ID,A.Person_Name,A.Organ_Id,A.Status_Id
FROM JZ_MONTH_FINISH_APPLYS B,JZ_INCOMECHECK_STATUS EA, JZ_APP A 
WHERE ( (TRUNC(EA.UPDATE_TIME) < TRUNC(B.CREATE_TIME) 
AND TRUNC(B.NEXT_MONTH_TIME) = TRUNC(to_date('2018-03','YYYY-MM')) AND B.ORGAN_ID = A.ORGAN_ID 
AND (EA.RECEIVE_STATUS = '07'  )) )
AND A.ENTRUST_ID = EA.ENTRUST_ID 
AND A.STATUS_ID = 's002' AND A.MANAGE_PROGRAM_ID = '00010001' AND A.ORGAN_ID = '0026102000'
UNION  ALL   
SELECT B.CETF_ID,B.Person_Name,B.Organ_Id,B.Status_Id  
FROM JZ_INCOMECHECK_ENTRUST_APP EP, JZ_APP B  
WHERE EP.ENTRUST_ID = B.ENTRUST_ID  
AND EP.RECEIVE_STATUS IN ('09', '04')  
AND B.STATUS_ID = 's002' AND B.MANAGE_PROGRAM_ID = '00010001'  AND B.ORGAN_ID = '0026102000'

--变动审核
			SELECT A.CETF_ID,A.Person_Name,A.Organ_Id,A.Status_Id 
			FROM JZ_MONTH_FINISH_APPLYS B,JZ_INCOMECHECK_STATUS EA, JZ_APP A 
			WHERE ( (TRUNC(EA.UPDATE_TIME) < TRUNC(B.CREATE_TIME) 
			AND TRUNC(B.NEXT_MONTH_TIME) = TRUNC(?) AND B.ORGAN_ID = A.ORGAN_ID 
			AND (EA.RECEIVE_STATUS = ?  )) )
			AND A.ENTRUST_ID = EA.ENTRUST_ID 
			AND A.STATUS_ID IN (?,?) AND A.MANAGE_PROGRAM_ID = ? AND A.ORGAN_ID = ? 
			UNION  ALL  
			SELECT B.CETF_ID,B.Person_Name,B.Organ_Id,B.Status_Id 
			FROM JZ_INCOMECHECK_ENTRUST_APP EP, JZ_APP B 
			WHERE EP.ENTRUST_ID = B.ENTRUST_ID 
			AND EP.RECEIVE_STATUS IN (?,?) 
			AND B.STATUS_ID IN (?,?)  AND B.MANAGE_PROGRAM_ID = ?  AND B.ORGAN_ID = ? 
--不定期变动
SELECT *
  FROM JZ_APP
 WHERE STATUS_ID IN (?, ?)
   AND MANAGE_PROGRAM_ID = ?
   AND ORGAN_ID = ?
--街镇审批
SELECT * FROM JZ_APP WHERE STATUS_ID = ? 
AND MANAGE_PROGRAM_ID = ? AND ORGAN_ID = ?
--复审
SELECT * FROM JZ_APP T WHERE T.STATUS_ID LIKE 'Y%' 
AND T.MANAGE_PROGRAM_ID = ? AND TRUNC(T.REVIEW_DATE) <= TRUNC(?) AND T.ORGAN_ID = ?
--下月年满17周岁人员
select A.CETF_ID,A.Person_Name,A.Organ_Id,A.Status_Id 
	from JZ_APP A, JZ_BASIC_PERSON P WHERE A.FAMILY_ID = P.FAMILY_ID 
	AND months_between(trunc(?,'month'),decode(p.credentials_type,'01',to_date(substr(p.cetf_id,7,6),'yyyymm'),trunc(p.birthdate,'month')))/12=17
	AND (P.status = '00' or P.status = '') 
	AND A.STATUS_ID like 'Y%' 
	AND (P.NC_OBJ_TYPE = '00010018' OR P.PERSON_OBJ_TYPE = '00010018') 
	AND P.ORGAN_ID = ? AND A.MANAGE_PROGRAM_ID = ? AND A.ORGAN_ID = ?

--重残无业待终止
SELECT A.CETF_ID,A.Person_Name,A.Organ_Id,A.Status_Id 
FROM JZ_APP A, IMPORT_DATA_ZCWY I, JZ_APP_ZCWYIMPORT_MAPPING Z 
WHERE I.IMPORT_ID = Z.IMPORT_ID AND A.APP_NO = Z.APP_NO AND I.TYPE = '03' 
AND A.STATUS_ID LIKE 'Y%' AND A.MANAGE_PROGRAM_ID = '00010050' AND A.ORGAN_ID = '0026102000'

--重残无业人员待迁出人数
SELECT * FROM JZ_APP A, IMPORT_DATA_ZCWY I, JZ_APP_ZCWYIMPORT_MAPPING M 
WHERE I.IMPORT_ID = M.IMPORT_ID AND M.APP_NO = A.APP_NO AND M.STATUS <> '2'
AND A.STATUS_ID LIKE 'Y%' AND I.TYPE = '04' AND A.RESIDE_ORGAN NOT LIKE TRIM(I.NRPR_ORGAN) || '%' 
 AND A.ORGAN_ID = '0026102000' 
 
--临时救助待审核/待审批
SELECT CETF_ID,Person_Name,Organ_Id,Status_Id  FROM JZ_APP WHERE STATUS_ID = 's002' 
AND APPLY_DATE <= to_date('20180914','yyyymmdd') 
AND MANAGE_PROGRAM_ID = '00010200' AND ORGAN_ID = '0026102000' 
--临时救助待审批
SELECT CETF_ID,Person_Name,Organ_Id,Status_Id FROM JZ_APP WHERE STATUS_ID = ? 
AND MANAGE_PROGRAM_ID = ? AND ORGAN_ID = ? 
--特困人员供养 待新受理审核
		SELECT A.CETF_ID,A.Person_Name,A.Organ_Id,A.Status_Id  
		FROM JZ_MONTH_FINISH_APPLYS B,JZ_INCOMECHECK_STATUS EA, JZ_APP A 
		WHERE ( (TRUNC(EA.UPDATE_TIME) < TRUNC(B.CREATE_TIME) 
		AND TRUNC(B.NEXT_MONTH_TIME) = TRUNC(?) AND B.ORGAN_ID = A.ORGAN_ID 
		AND (EA.RECEIVE_STATUS = ?  )) )
		AND A.ENTRUST_ID = EA.ENTRUST_ID 
		AND A.STATUS_ID = ? AND A.MANAGE_PROGRAM_ID = ? AND A.ORGAN_ID = ? 
		UNION  ALL  
		SELECT B.CETF_ID,B.Person_Name,B.Organ_Id,B.Status_Id
		FROM JZ_INCOMECHECK_ENTRUST_APP EP, JZ_APP B 
		WHERE EP.ENTRUST_ID = B.ENTRUST_ID  
		AND EP.RECEIVE_STATUS IN (?,?) 
		AND B.STATUS_ID = ? AND B.MANAGE_PROGRAM_ID = ? AND B.ORGAN_ID = ? 
--特困新受理审批
SELECT * FROM JZ_APP WHERE STATUS_ID = ? AND MANAGE_PROGRAM_ID = ? AND ORGAN_ID = ?
--特困人员供养待复核审核
		SELECT A.CETF_ID,A.Person_Name,A.Organ_Id,A.Status_Id 
		FROM JZ_MONTH_FINISH_APPLYS B,JZ_INCOMECHECK_STATUS EA, JZ_APP A 
		WHERE ( (TRUNC(EA.UPDATE_TIME) < TRUNC(B.CREATE_TIME) 
		AND TRUNC(B.NEXT_MONTH_TIME) = TRUNC(?) AND B.ORGAN_ID = A.ORGAN_ID 
		AND (EA.RECEIVE_STATUS = ?  )) )
		AND A.ENTRUST_ID = EA.ENTRUST_ID 
		AND A.STATUS_ID = ? AND A.MANAGE_PROGRAM_ID = ?  AND A.ORGAN_ID = ? 
		UNION  ALL  
		SELECT B.CETF_ID,B.Person_Name,B.Organ_Id,B.Status_Id 
		FROM JZ_INCOMECHECK_ENTRUST_APP EP, JZ_APP B  
		WHERE EP.ENTRUST_ID = B.ENTRUST_ID 
		AND EP.RECEIVE_STATUS IN (?,?)  
		AND B.STATUS_ID = ? AND B.MANAGE_PROGRAM_ID = ? AND B.ORGAN_ID = ?
--特困人员复核审批
SELECT CETF_ID,Person_Name,Organ_Id,Status_Id 
FROM JZ_APP WHERE STATUS_ID = ? AND MANAGE_PROGRAM_ID = ? AND ORGAN_ID = ? 
--特困人员供养复审
SELECT CETF_ID,Person_Name,Organ_Id,Status_Id FROM JZ_APP T WHERE T.STATUS_ID LIKE 'Y%' 
AND T.MANAGE_PROGRAM_ID = ? AND TRUNC(T.REVIEW_DATE) <= TRUNC(?) AND T.ORGAN_ID = ?
-- 特困人员供养待复审审核 
		SELECT A.CETF_ID,A.Person_Name,A.Organ_Id,A.Status_Id 
		FROM JZ_MONTH_FINISH_APPLYS B,JZ_INCOMECHECK_STATUS EA, JZ_APP A 
		WHERE ( (TRUNC(EA.UPDATE_TIME) < TRUNC(B.CREATE_TIME) 
		AND TRUNC(B.NEXT_MONTH_TIME) = TRUNC(?) AND B.ORGAN_ID = A.ORGAN_ID 
		AND (EA.RECEIVE_STATUS = ?  )) )
		AND A.ENTRUST_ID = EA.ENTRUST_ID 
		AND A.STATUS_ID = ? AND A.MANAGE_PROGRAM_ID = ? AND A.ORGAN_ID = ? 
		UNION  ALL  
		SELECT B.CETF_ID,B.Person_Name,B.Organ_Id,B.Status_Id 
		FROM JZ_INCOMECHECK_ENTRUST_APP EP, JZ_APP B 
		WHERE EP.ENTRUST_ID = B.ENTRUST_ID 
		AND EP.RECEIVE_STATUS IN (?,?) 
		AND B.STATUS_ID =? AND B.MANAGE_PROGRAM_ID = ? AND B.ORGAN_ID = ? 
--特困人员复审审批
SELECT  CETF_ID,Person_Name,Organ_Id,Status_Id  FROM JZ_APP 
WHERE STATUS_ID = ? AND MANAGE_PROGRAM_ID = ? AND ORGAN_ID = ? 
--特困人员变动审核
SELECT A.CETF_ID,A.Person_Name,A.Organ_Id,A.Status_Id 
FROM JZ_MONTH_FINISH_APPLYS B,JZ_INCOMECHECK_STATUS EA, JZ_APP A 
WHERE ( (TRUNC(EA.UPDATE_TIME) < TRUNC(B.CREATE_TIME) 
AND TRUNC(B.NEXT_MONTH_TIME) = TRUNC(?) AND B.ORGAN_ID = A.ORGAN_ID 
AND (EA.RECEIVE_STATUS = ?  )) )
AND A.ENTRUST_ID = EA.ENTRUST_ID 
AND A.STATUS_ID IN (?) 
AND A.MANAGE_PROGRAM_ID = ? 
AND A.ORGAN_ID = ? 
UNION  ALL  
SELECT B.CETF_ID,B.Person_Name,B.Organ_Id,B.Status_Id 
FROM JZ_INCOMECHECK_ENTRUST_APP EP, JZ_APP B 
WHERE EP.ENTRUST_ID = B.ENTRUST_ID 
AND EP.RECEIVE_STATUS IN (?,?) 
AND B.STATUS_ID = ? AND B.MANAGE_PROGRAM_ID = ? AND B.ORGAN_ID = ? 
--特困变动审批
SELECT CETF_ID,Person_Name,Organ_Id,Status_Id FROM JZ_APP 
WHERE STATUS_ID = ? AND MANAGE_PROGRAM_ID = ? AND ORGAN_ID = ?
--住院医疗审核
SELECT NVL(SUM(COUNT), 0) COUNT FROM ( 
			+ " SELECT NVL(COUNT(1),0) COUNT "
			+ " FROM JZ_MONTH_FINISH_APPLYS B,JZ_INCOMECHECK_STATUS EA, JZ_APP A "
			+ " WHERE ((TRUNC(EA.UPDATE_TIME) < TRUNC(B.CREATE_TIME) "
			+ " AND TRUNC(B.NEXT_MONTH_TIME) = TRUNC(?) AND B.ORGAN_ID = A.ORGAN_ID "
			+ " AND (EA.RECEIVE_STATUS = ?  )))"
			+ " AND A.ENTRUST_ID = EA.ENTRUST_ID "
			+ " AND A.STATUS_ID IN (?,?) "
			+ " AND A.MANAGE_PROGRAM_ID = ? "
			+ " AND A.ORGAN_ID = ? "
			+ " UNION  ALL  " 
			+ " SELECT NVL(COUNT(1), 0) COUNT " 
			+ " FROM JZ_INCOMECHECK_ENTRUST_APP EP, JZ_APP B " 
			+ " WHERE EP.ENTRUST_ID = B.ENTRUST_ID " 
			+ " AND EP.RECEIVE_STATUS IN (?,?) " 
			+ " AND B.STATUS_ID IN (?,?) " 
			+ " AND B.MANAGE_PROGRAM_ID = ? " 
			+ " AND B.ORGAN_ID = ? " +
					" UNION ALL " +
					" SELECT NVL(COUNT(1), 0) COUNT " 
			+ " FROM JZ_APP B " 
			+ " WHERE B.ENTRUST_ID IS NULL " 
			+ " AND B.STATUS_ID IN (?,?) " 
			+ " AND B.MANAGE_PROGRAM_ID = ? " 
			+ " AND B.ORGAN_ID = ? ) ";


